keywords = [
    "Management and Business Professionals and Administrative Services",
    "Management advisory services",
    "Business and corporate management consultation services",
    "New business start up consultation services",
    "Corporate mergers consultation services",
    "Corporate divestiture consultation services",
    "Strategic planning consultation services",
    "Corporate objectives or policy development",
    "Organizational structure consultation",
    "Information technology consultation services",
    "Business intelligence consulting services",
    "Government affairs and community relations consultation service",
    "Risk management consultation service",
    "Human resources consulting service",
    "Actuarial consulting services",
    "Process and procedures management consultation service",
    "Project management",
    "Feasibility studies or screening of project ideas",
    "Regional or location studies for projects",
    "Economic or financial evaluation of projects",
    "Project administration or planning",
    "Temporary drafting service",
    "Project monitoring and evaluation",
    "Project impact assessment",
    "Industrial management",
    "Productivity or efficiency studies or implementation",
    "Specification standardization services",
    "Supply chain analysis or re engineering services",
    "Professional procurement services",
    "Human resources services",
    "Human resource development",
    "Management development",
    "Compensation or benefits planning",
    "Labor or union relations",
    "Labor training or development",
    "Human resources productivity audits",
    "Personnel relocation",
    "Outplacement services",
    "Service recognition programs",
    "Job evaluation service",
    "Job description development and writing service",
    "Labor training impact assessment",
    "Public relations and professional communications services",
    "Situation and stakeholder analysis and communications planning services",
    "Polling and survey and public opinion monitoring and analysis",
    "Focus group and public feedback meeting facilitation and analysis",
    "Public relations situation and issues and risk analysis",
    "Stakeholder analysis",
    "Communication planning",
    "Stakeholder management and relations services",
    "Investor and shareholder relations consultation and engagement",
    "Internal stakeholder relations consultation and engagement",
    "Cultural and ethnic group relations consultation and engagement",
    "Indigenous peoples relations consultation and engagement",
    "Government relations consultation and engagement",
    "Community relations consultation and engagement",
    "Not for profit organization relations consultation and engagement",
    "Business and utility provider relations consultation and engagement",
    "Professional communication services",
    "Internal communication service",
    "Project based communications service",
    "Public affairs service",
    "Issues and crisis management services",
    "Crisis management and recovery service",
    "Crisis planning and avoidance service",
    "Change management communication and advisory service",
    "Issues management and mitigation advisory service",
    "Engineering and Research and Technology Based Services",
    "Computer services",
    "Software or hardware engineering",
    "Mainframe software applications design",
    "Personal computer PC application design",
    "Systems integration design",
    "Application programming services",
    "Operating system programming services",
    "Client or server programming services",
    "ERP or database applications programming services",
    "Application implementation services",
    "Internet or intranet client application development services",
    "Internet or intranet server application development services",
    "System or application programming management service",
    "Computer graphics service",
    "Management information systems MIS",
    "Wide area network communications design",
    "Local area network communications design",
    "Electronic data interchange EDI design",
    "Database design",
    "Systems architecture",
    "Network planning services",
    "Systems planning services",
    "Telecommunications planning services",
    "Demining geographical or geospatial information system GIS",
    "System and system component administration services",
    "Database analysis service",
    "System analysis service",
    "Economics",
    "Economic analysis",
    "Macro economic analysis",
    "Micro economic analysis",
    "Econometrics",
    "Economic forecasts",
    "Economic development consultancy",
    "Financial and Insurance Services",
    "Accounting and bookkeeping services",
    "Accounting services",
    "Audit services",
    "Corporate finance",
    "Taxation issues and preparation",
    "business performance", "risk management", "compliance", "strategy development",
    "value enhancement", "cyber security", "data analytics", "human capital", 
    "audit solutions", "technology-enhanced audit", "analytics", "tax compliance", 
    "international tax", "mergers and acquisitions tax", "tax transformation", 
    "cloud management", "consultancy", "Conseil",
    "consulting", "Consultoría", "Consultoria", "Consultation",
    "advisory", "Asesoramiento", "Consultivo", "Consultatif",
    "evaluation", "Evaluación", "Avaliação", 
    "audit", "Auditoría", "Auditoria", 
    "assessment", "Évaluation",
    "feasibility study", "Estudio de viabilidad", "Estudo de viabilidade", "Étude de faisabilité",
    "independent verification", "Verificación independiente", "Verificação independente", "Vérification indépendante",
    "third-party monitoring", "Monitoreo de terceros", "Monitoramento de terceiros", "Surveillance par une tierce partie",
    "strategic", "Estratégico", "Stratégique"
]
